### ISSUE TITLE
How can use the bot to edit a message?

### ISSUE THREAD

**Issue by bndynet** [WebexCommunity/webex-node-bot-framework#100]
I want to use this framework to send a message, and then to change this message. But I cannot find which function to do this.

**Comment by jpjpjp** [comment]
Hi @bndynet.  Best place to get help with the framework is ["Webex Node Bot Framework" space on Webex](https://eurl.io/#BJ7gmlSeU)

There are several helper functions to send messages, the most common one being [bot.say()](https://github.com/WebexCommunity/webex-node-bot-framework#botsayformat-message--promisemessage).   

The framework does not provide a helper method for editing a message yet, but you can call (bot.getWebexSDK())[https://github.com/WebexCommunity/webex-node-bot-framework#botsayformat-message--promisemessage] and then call the SDK's [update message](https://webex.github.io/webex-js-sdk/api/#messages) method.

**Comment by bndynet** [comment]
Thanks @jpjpjp for your reply. I found the **update** function was added since version 2.49. But this framework is still using version  **2.29.3**.  Do you have any plans to upgrade to the newer version?

<img width="1107" alt="image" src="https://github.com/WebexCommunity/webex-node-bot-framework/assets/3853678/1a6cefa1-db50-4388-a6dc-a54a48ecd3fa">

<img width="451" alt="image" src="https://github.com/WebexCommunity/webex-node-bot-framework/assets/3853678/ebb296aa-4765-4379-a955-e31bccf14a9d">

**Comment by jpjpjp** [comment]
Hi @bndynet.  Unfortunately, newer versions of the SDK are causing the framework's tests to fail.   I haven't been able to resolve those issues.  The version I have is the last one that seems to work.

It is still possible for your app to update a message but I think you would have to use the requests library (or something similar) to make a call to the [Update Message REST API](https://developer.webex.com/docs/api/v1/messages/edit-a-message)

**Comment by bndynet** [comment]
> Hi @bndynet. Unfortunately, newer versions of the SDK are causing the framework's tests to fail. I haven't been able to resolve those issues. The version I have is the last one that seems to work.
> 
> It is still possible for your app to update a message but I think you would have to use the requests library (or something similar) to make a call to the [Update Message REST API](https://developer.webex.com/docs/api/v1/messages/edit-a-message)

Got it, thanks again @jpjpjp .  I copied the update method code from SDK, and it works now. Have a nice weekend and thanks all your team for contributing this great tool.
