### ISSUE TITLE
"Preference" not respected when bot hears message that matches two handlers

### ISSUE THREAD

**Issue by RobM-ADP** [WebexCommunity/webex-node-bot-framework#81]
It seems that the "preference" argument as described here does not work as documented:
https://github.com/WebexCommunity/webex-node-bot-framework#framework

The documentation says:
> Specifies preference of phrase action when overlapping phrases are matched. On multiple matches with same preference, all matched actions are excuted. On multiple matches with difference preference values, only the lower preferenced matched action(s) are executed.

However, when implemented like this:
```
framework.hears('help', (bot: any, trigger: any) => {
    bot.say(framework.showHelp());
  }, 'help - shows information about commands I understand', 1);

  framework.hears(/.*/gim, (bot: any, trigger: any) => {
    bot.say('I didn\'t quite understand that.');
  }, null, 2);
  ```
  Sending the message "help" results in it responding with "I didn't quite understand that" instead of returning the help message.

**Comment by RobM-ADP** [comment]
Apparently, this is more of a documentation issue. It isn't clear from the docs that if you don't want a help message but you do want a preference, you should just omit the help (rather than set to null as I did above). So the correct way to do this would be:
```
framework.hears('help', (bot: any, trigger: any) => {
    bot.say(framework.showHelp());
  }, 'help - shows information about commands I understand', 1);

  framework.hears(/.*/gim, (bot: any, trigger: any) => {
    bot.say('I didn\'t quite understand that.');
  }, 2);
```

**Comment by jpjpjp** [comment]
@RobM-ADP, thanks very much for the feedback.   I'll take a look at the docs to see if this can be made clearer as I merge the changes in your recent PR.
